CREATE TABLE ads
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titre            VARCHAR(255),
    description      VARCHAR(2000),
    date_publication TIMESTAMP WITHOUT TIME ZONE,
    room_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_ads PRIMARY KEY (id)
);

CREATE TABLE photos
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url   VARCHAR(255),
    ad_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_photos PRIMARY KEY (id)
);

CREATE TABLE properties
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    adresse         VARCHAR(255),

    ville           VARCHAR(255),
    latitude        DOUBLE PRECISION,
    longitude       DOUBLE PRECISION,
    description     VARCHAR(2000),
    rules           VARCHAR(2000),
    CONSTRAINT pk_properties PRIMARY KEY (id)
);

CREATE TABLE rooms
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    superficie    DOUBLE PRECISION,
    prix          DOUBLE PRECISION,
    disponibilite BOOLEAN,
    property_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_rooms PRIMARY KEY (id)
);

ALTER TABLE ads
    ADD CONSTRAINT FK_ADS_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);

ALTER TABLE photos
    ADD CONSTRAINT FK_PHOTOS_ON_AD FOREIGN KEY (ad_id) REFERENCES ads (id);

ALTER TABLE rooms
    ADD CONSTRAINT FK_ROOMS_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);